#!/usr/bin/env sh
#
# Author: lucyssue
# Rather small script to launch dmenu using the user pywal theme, if applicable.

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

dmenu_run -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -s -p "Search..."
